import 'dart:io';

import 'package:flutter/foundation.dart';

class HissLocal{
  static const String maxAdKeyBase64="TVdKemhuRVB0S3F4TEtSTEFsVnJUeVFmTzJWeFdaV3RWeF9TelRXQ19NZ29aTDdrVEtOdDl0M01fT2dJWjI0bkJYUlh4VmQ5b2dRRXA3NjE2VFdmM0M=";

  static const _androidIntAdId="a9af74c92e3925ae";
  static const _iosIntAdId="11436a365bfa5635";
  static String intAdId=Platform.isAndroid?_androidIntAdId:_iosIntAdId;

  static const _androidRvAdId="01613654bd67b3e4";
  static const _iosRvAdId="f2b4c129d2be6181";
  static String rvAdId=Platform.isAndroid?_androidRvAdId:_iosRvAdId;

  static const _androidPrivacy="https://sites.google.com/view/privacypolicy134/home";
  static const _iosPrivacy="https://hisssolitairexmaspro.com/privacy/";
  static String privacyUrl=Platform.isAndroid?_androidPrivacy:_iosPrivacy;


  static const String taskQueueConfigLocalStrBase64="ewogICAgImRhaWx5X3Rhc2siOiBbCiAgICAgICAgewogICAgICAgICAgICAibmFtZSI6ICJnYW1lIiwKICAgICAgICAgICAgIm51bSI6IDEsCiAgICAgICAgICAgICJhd2FyZCI6IDUwCiAgICAgICAgfSwKICAgICAgICB7CiAgICAgICAgICAgICJuYW1lIjogImNhcmQiLAogICAgICAgICAgICAibnVtIjogMTAsCiAgICAgICAgICAgICJhd2FyZCI6IDUwCiAgICAgICAgfSwKICAgICAgICB7CiAgICAgICAgICAgICJuYW1lIjogInRvb2wiLAogICAgICAgICAgICAibnVtIjogNSwKICAgICAgICAgICAgImF3YXJkIjogMjAKICAgICAgICB9LAogICAgICAgIHsKICAgICAgICAgICAgIm5hbWUiOiAiYnViYmxlcyIsCiAgICAgICAgICAgICJudW0iOiAyLAogICAgICAgICAgICAiYXdhcmQiOiAyMAogICAgICAgIH0sCiAgICAgICAgewogICAgICAgICAgICAibmFtZSI6ICJyYW5rIiwKICAgICAgICAgICAgIm51bSI6IDEsCiAgICAgICAgICAgICJhd2FyZCI6IDIwMAogICAgICAgIH0KICAgIF0sCiAgICAid2l0aGRyYXdhbF90YXNrIjogWwogICAgICAgIHsKICAgICAgICAgICAgIm5hbWUiOiAiY2FyZCIsCiAgICAgICAgICAgICJudW0iOiA1CiAgICAgICAgfSwKICAgICAgICB7CiAgICAgICAgICAgICJuYW1lIjogInRvb2wiLAogICAgICAgICAgICAibnVtIjogNQogICAgICAgIH0sCiAgICAgICAgewogICAgICAgICAgICAibmFtZSI6ICJnYW1lIiwKICAgICAgICAgICAgIm51bSI6IDEKICAgICAgICB9LAogICAgICAgIHsKICAgICAgICAgICAgIm5hbWUiOiAiYnViYmxlcyIsCiAgICAgICAgICAgICJudW0iOiAzCiAgICAgICAgfSwKICAgICAgICB7CiAgICAgICAgICAgICJuYW1lIjogInB1enpsZSIsCiAgICAgICAgICAgICJudW0iOiAxMAogICAgICAgIH0KICAgIF0sCiAgICAiZ2lmdF90YXNrX3B1enpsZV9udW0iOiAxMCwKICAgICJxdWV1ZSI6IHsKICAgICAgICAibV9tIjogWwogICAgICAgICAgICA1LAogICAgICAgICAgICA4CiAgICAgICAgXSwKICAgICAgICAic19zIjogWwogICAgICAgICAgICAyNSwKICAgICAgICAgICAgMzUKICAgICAgICBdCiAgICB9Cn0=";


  static const String _androidTbaUrl="";
  static const String _iosTbaUrl="https://jensen.hisssolitairexmaspro.com/colorate/austin/noisome";
  static String tbaUrl=Platform.isAndroid?_androidTbaUrl:_iosTbaUrl;
}